/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mariomaker;

import estructuras.ListaDoble;
import estructuras.MatrizOrtogonal;

/**
 * @author Adrian Fernando Burgos Herrera
 * 2011 14683
 */

public class ModoSeleccion extends javax.swing.JFrame {

    ListaDoble listaObjetos;
    MatrizOrtogonal matriz = new MatrizOrtogonal();
    
    public ModoSeleccion(ListaDoble listaObjetos) {
        initComponents();
        this.listaObjetos = listaObjetos;
    }

    
    ModoSeleccion(String seleccionar_tipo_de_estructura) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pila.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 240, 106, 109);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cola.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 240, 106, 109);

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(lFondo);
        lFondo.setBounds(0, 0, 800, 450);

        setSize(new java.awt.Dimension(816, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //la lista trabaja como una pila
        listaObjetos.setTipoEstrcutura(1);
        HiloConstruccion construccion = new HiloConstruccion(listaObjetos, matriz);
        construccion.iniciar();
//        matriz.agregarFila();
//        matriz.agregarColumna();
//        matriz.agregarFila();        
//        matriz.agregarColumna();
//        matriz.agregarFila();
//        matriz.agregarColumna();
//        matriz.agregarColumna();
//        System.out.println(matriz.recorrido());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //la lista trabaja como una cola
        listaObjetos.setTipoEstrcutura(2);
        HiloConstruccion construccion = new HiloConstruccion(listaObjetos, matriz);
        construccion.iniciar();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lFondo;
    // End of variables declaration//GEN-END:variables
}
