package mariomaker;

import estructuras.ListaDoble;
import estructuras.NodoSimple;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JApplet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 * @author Adrian Fernando Burgos Herrera
 * 2011 14683
 */

public class Principal extends javax.swing.JFrame {

    ListaDoble listaObjetos = new ListaDoble();
    public static boolean luigi = false;
    public static boolean meta = false;
    public ModoSeleccion modoSeleccion = new ModoSeleccion(listaObjetos);
    //VistaPrevia vistaPrevia = new VistaPrevia();
    SpriteSheet sheet;
    BufferedImage imagen = null;
    HiloVista vista;
    private final int ancho = 25, alto = 25, espacio = 84;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public boolean estaLuigi() {
        return luigi;
    }

    public void setLuigi(boolean luigi) {
        this.luigi = luigi;
    }

    public boolean estaMeta() {
        return meta;
    }

    public void setMeta(boolean meta) {
        this.meta = meta;
    }
    
    private void insertarObjeto(String nombre, int tipo)
    {
        Elemento nuevoElemento = null;
        if(tipo != -1)
        {
            //se crea el elemento
            nuevoElemento = new Elemento(nombre, tipo);
            switch (tipo)
            {
                case 7:
                    if(estaLuigi())
                    {
                        JOptionPane.showMessageDialog(null, "El Personaje principal \"(Luigi)\" ya esta agregado");
                        return;
                    }
                    else
                        setLuigi(true);
                    break;
                case 8:
                    if(estaMeta())
                    {
                        JOptionPane.showMessageDialog(null, "El Castillo \"(Meta)\" ya esta agregado");
                        return;
                    }
                    else
                        setMeta(true);
                    break;
            }
            listaObjetos.insertar(nuevoElemento);
        }
    }
    
    public int radioButtonSeleccionado()
    {
        if(rbSuelo.isSelected())
            return 1;
        if(rbPared.isSelected())
            return 2;
        if(rbFicha.isSelected())
            return 3;
        if(rbVida.isSelected())
            return 4;
        if(rbGoomba.isSelected())
            return 5;
        if(rbKoopa.isSelected())
            return 6;
        if(rbPersonaje.isSelected())
            return 7;
        if(rbCastillo.isSelected())
            return 8;
        //si no se tiene ningu radio button seleccionado
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        lNombre = new javax.swing.JLabel();
        bAgregar = new javax.swing.JButton();
        lImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tbNombre = new javax.swing.JTextField();
        bVistaPrevia = new javax.swing.JButton();
        rbSuelo = new javax.swing.JRadioButton();
        rbCastillo = new javax.swing.JRadioButton();
        rbPersonaje = new javax.swing.JRadioButton();
        rbKoopa = new javax.swing.JRadioButton();
        rbGoomba = new javax.swing.JRadioButton();
        rbVida = new javax.swing.JRadioButton();
        rbFicha = new javax.swing.JRadioButton();
        rbPared = new javax.swing.JRadioButton();
        lFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carga de objetos");
        getContentPane().setLayout(null);

        lNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nombre.png"))); // NOI18N
        getContentPane().add(lNombre);
        lNombre.setBounds(420, 290, 100, 20);

        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        bAgregar.setContentAreaFilled(false);
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar);
        bAgregar.setBounds(450, 240, 30, 30);
        getContentPane().add(lImagen);
        lImagen.setBounds(452, 200, 25, 25);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/finalizar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 410, 150, 30);
        getContentPane().add(tbNombre);
        tbNombre.setBounds(420, 310, 100, 20);

        bVistaPrevia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar_1.png"))); // NOI18N
        bVistaPrevia.setContentAreaFilled(false);
        bVistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVistaPreviaActionPerformed(evt);
            }
        });
        getContentPane().add(bVistaPrevia);
        bVistaPrevia.setBounds(662, 32, 26, 26);

        Grupo1.add(rbSuelo);
        rbSuelo.setText("Suelo");
        rbSuelo.setContentAreaFilled(false);
        rbSuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSueloActionPerformed(evt);
            }
        });
        getContentPane().add(rbSuelo);
        rbSuelo.setBounds(220, 240, 140, 23);

        Grupo1.add(rbCastillo);
        rbCastillo.setText("Castillo");
        rbCastillo.setContentAreaFilled(false);
        getContentPane().add(rbCastillo);
        rbCastillo.setBounds(220, 380, 140, 20);

        Grupo1.add(rbPersonaje);
        rbPersonaje.setText("Personaje principal");
        rbPersonaje.setContentAreaFilled(false);
        getContentPane().add(rbPersonaje);
        rbPersonaje.setBounds(220, 360, 140, 20);

        Grupo1.add(rbKoopa);
        rbKoopa.setText("Koopa");
        rbKoopa.setContentAreaFilled(false);
        getContentPane().add(rbKoopa);
        rbKoopa.setBounds(220, 340, 140, 20);

        Grupo1.add(rbGoomba);
        rbGoomba.setText("Goomba");
        rbGoomba.setContentAreaFilled(false);
        getContentPane().add(rbGoomba);
        rbGoomba.setBounds(220, 320, 140, 20);

        Grupo1.add(rbVida);
        rbVida.setText("Vida");
        rbVida.setContentAreaFilled(false);
        getContentPane().add(rbVida);
        rbVida.setBounds(220, 300, 140, 23);

        Grupo1.add(rbFicha);
        rbFicha.setText("Ficha");
        rbFicha.setContentAreaFilled(false);
        getContentPane().add(rbFicha);
        rbFicha.setBounds(220, 280, 140, 23);

        Grupo1.add(rbPared);
        rbPared.setText("Pared");
        rbPared.setContentAreaFilled(false);
        getContentPane().add(rbPared);
        rbPared.setBounds(220, 260, 140, 23);

        lFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(lFondo);
        lFondo.setBounds(0, 0, 800, 450);

        setSize(new java.awt.Dimension(816, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbSueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSueloActionPerformed
    
    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        /*
         * Agrega los objetos a la lista de obejetos
         */
        int seleccionado = radioButtonSeleccionado();
        insertarObjeto(tbNombre.getText(), seleccionado);
        
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bVistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVistaPreviaActionPerformed
        HiloVista.cambio = true;
        vista = new HiloVista(listaObjetos);
        vista.iniciar();
        System.out.println(listaObjetos.recorrido());
    }//GEN-LAST:event_bVistaPreviaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modoSeleccion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bVistaPrevia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lFondo;
    public javax.swing.JLabel lImagen;
    private javax.swing.JLabel lNombre;
    private javax.swing.JRadioButton rbCastillo;
    private javax.swing.JRadioButton rbFicha;
    private javax.swing.JRadioButton rbGoomba;
    private javax.swing.JRadioButton rbKoopa;
    private javax.swing.JRadioButton rbPared;
    private javax.swing.JRadioButton rbPersonaje;
    private javax.swing.JRadioButton rbSuelo;
    private javax.swing.JRadioButton rbVida;
    private javax.swing.JTextField tbNombre;
    // End of variables declaration//GEN-END:variables
}
